//! Boostify AI Engine client — talks to the private FastAPI inference server
//! (running on the H200/H100) to generate images (FLUX / Qwen), video
//! (LTX-2.3 / Wan2.2) and music (ACE-Step) with the artist's own installed
//! models.
//!
//! The engine exposes an async job API:
//!   * `POST /{domain}/generate`  -> `{ job_id, status_url }`
//!   * `POST /{domain}/status` `{job_id}` -> `JobStatus { completed, failed, … }`
//!   * output files are served at `/files/{domain}/{job_id}/{file}`
//! authenticated with the `x-api-key` header.
//!
//! This module hides that flow behind simple blocking helpers that return the
//! generated bytes, so the video-editor orchestration in `lib.rs` can swap the
//! NVIDIA cloud / local Ken Burns path for the real installed models whenever an
//! engine URL is configured in Settings. It is deliberately pure: no DB access.

use std::io::Read;
use std::time::Duration;

use base64::Engine as _;
use serde_json::{json, Value};

use crate::models::*;

/// Seconds between status polls.
const POLL_SECS: u64 = 4;
/// Max polls (~15 min) — heavy video generation can be slow.
const POLL_MAX: u32 = 225;

/// Resolve the engine base URL from settings (trimmed, no trailing slash).
/// Returns `None` when no engine is configured.
pub fn base_url(s: &AppSettings) -> Option<String> {
    let u = s.ai_engine_url.trim().trim_end_matches('/').to_string();
    if u.is_empty() {
        None
    } else {
        Some(u)
    }
}

fn api_key(s: &AppSettings) -> String {
    s.ai_engine_key.trim().to_string()
}

/// True when an engine URL is set (the app should prefer installed models).
pub fn is_configured(s: &AppSettings) -> bool {
    base_url(s).is_some()
}

fn post(base: &str, key: &str, path: &str, body: Value, timeout: u64) -> Result<Value, String> {
    let mut req = ureq::post(&format!("{base}{path}"))
        .set("Accept", "application/json")
        .set("Content-Type", "application/json")
        .timeout(Duration::from_secs(timeout));
    if !key.is_empty() {
        req = req.set("x-api-key", key);
    }
    match req.send_json(body) {
        Ok(r) => r.into_json().map_err(|e| format!("bad json: {e}")),
        Err(ureq::Error::Status(code, r)) => {
            let detail = r
                .into_string()
                .unwrap_or_default()
                .chars()
                .take(300)
                .collect::<String>();
            Err(format!("HTTP {code}: {detail}"))
        }
        Err(e) => Err(format!("request failed: {e}")),
    }
}

fn get_json(base: &str, key: &str, path: &str, timeout: u64) -> Result<Value, String> {
    let mut req = ureq::get(&format!("{base}{path}")).timeout(Duration::from_secs(timeout));
    if !key.is_empty() {
        req = req.set("x-api-key", key);
    }
    match req.call() {
        Ok(r) => r.into_json().map_err(|e| format!("bad json: {e}")),
        Err(ureq::Error::Status(code, r)) => {
            let detail = r.into_string().unwrap_or_default();
            Err(format!("HTTP {code}: {detail}"))
        }
        Err(e) => Err(format!("request failed: {e}")),
    }
}

fn get_bytes(base: &str, key: &str, path: &str) -> Result<Vec<u8>, String> {
    let mut req = ureq::get(&format!("{base}{path}")).timeout(Duration::from_secs(180));
    if !key.is_empty() {
        req = req.set("x-api-key", key);
    }
    match req.call() {
        Ok(r) => {
            let mut buf = Vec::new();
            r.into_reader()
                .read_to_end(&mut buf)
                .map_err(|e| format!("read failed: {e}"))?;
            if buf.is_empty() {
                Err("empty file".into())
            } else {
                Ok(buf)
            }
        }
        Err(e) => Err(format!("download failed: {e}")),
    }
}

/// Run a `generate` job for a domain and return the first output's bytes.
fn run_job(s: &AppSettings, domain: &str, body: Value) -> Result<Vec<u8>, String> {
    run_job_at(s, &format!("/{domain}/generate"), domain, body)
}

/// Like `run_job` but lets the caller pick the submit path (e.g. `/video/relight`)
/// while still polling `/{status_domain}/status` and downloading from `/files/…`.
fn run_job_at(
    s: &AppSettings,
    gen_path: &str,
    status_domain: &str,
    body: Value,
) -> Result<Vec<u8>, String> {
    let base = base_url(s).ok_or("AI engine URL not set")?;
    let key = api_key(s);

    let accepted = post(&base, &key, gen_path, body, 120)
        .map_err(|e| format!("engine {status_domain} generate: {e}"))?;
    let job_id = accepted
        .get("job_id")
        .and_then(|v| v.as_str())
        .ok_or("engine returned no job_id")?
        .to_string();
    let domain = status_domain;

    for _ in 0..POLL_MAX {
        std::thread::sleep(Duration::from_secs(POLL_SECS));
        let st = match post(
            &base,
            &key,
            &format!("/{domain}/status"),
            json!({ "job_id": job_id }),
            60,
        ) {
            Ok(v) => v,
            Err(_) => continue, // transient — keep polling
        };

        if st.get("failed").and_then(|v| v.as_bool()).unwrap_or(false) {
            let err = st
                .get("error")
                .and_then(|v| v.as_str())
                .unwrap_or("unknown");
            return Err(format!("engine {domain} job failed: {err}"));
        }

        if st.get("completed").and_then(|v| v.as_bool()).unwrap_or(false) {
            // Preferred: an absolute-ish output_url like /files/{domain}/{job_id}/{file}.
            if let Some(url) = st.get("output_url").and_then(|v| v.as_str()) {
                if !url.is_empty() {
                    if let Ok(b) = get_bytes(&base, &key, url) {
                        return Ok(b);
                    }
                }
            }
            // Fallback: reconstruct from output_files (relative names).
            if let Some(files) = st.get("output_files").and_then(|v| v.as_array()) {
                if let Some(f) = files.first().and_then(|v| v.as_str()) {
                    let url = format!("/files/{domain}/{job_id}/{f}");
                    if let Ok(b) = get_bytes(&base, &key, &url) {
                        return Ok(b);
                    }
                }
            }
            return Err(format!("engine {domain} completed but no downloadable output"));
        }
    }
    Err(format!("engine {domain} job timed out"))
}

// ---------------------------------------------------------------------------
// Public generation helpers
// ---------------------------------------------------------------------------

/// Generate a still image (PNG bytes) with an installed image model.
pub fn generate_image(
    s: &AppSettings,
    prompt: &str,
    model: &str,
    width: u32,
    height: u32,
    steps: u32,
    lora: Option<&str>,
    seed: i64,
) -> Result<Vec<u8>, String> {
    let mut body = json!({
        "prompt": prompt,
        "model": model,
        "kind": "promo",
        "width": width,
        "height": height,
        "steps": steps,
        "seed": seed,
    });
    if let Some(l) = lora {
        if !l.is_empty() {
            body["lora"] = json!(l);
        }
    }
    run_job(s, "image", body)
}

/// Edit an existing image (PNG/JPEG bytes) with a text instruction using an
/// installed edit-capable model (e.g. Qwen-Image-Edit). The source image is
/// sent as a base64 data URL in `reference_image`.
pub fn edit_image(
    s: &AppSettings,
    image: &[u8],
    prompt: &str,
    model: &str,
    steps: u32,
    seed: i64,
) -> Result<Vec<u8>, String> {
    let b64 = base64::engine::general_purpose::STANDARD.encode(image);
    let body = json!({
        "prompt": prompt,
        "model": model,
        "kind": "edit",
        "reference_image": format!("data:image/png;base64,{b64}"),
        "steps": steps,
        "seed": seed,
    });
    run_job(s, "image", body)
}

/// Generate a video clip (MP4 bytes) with an installed video model. When
/// `image_png` is provided it is sent as an image-to-video reference (base64
/// data URL); otherwise the call is pure text-to-video.
pub fn generate_video(
    s: &AppSettings,
    prompt: &str,
    model: &str,
    mode: &str,
    width: u32,
    height: u32,
    num_frames: u32,
    fps: u32,
    image_png: Option<&[u8]>,
    lora: Option<&str>,
    seed: i64,
) -> Result<Vec<u8>, String> {
    let mut body = json!({
        "prompt": prompt,
        "model": model,
        "mode": mode,
        "width": width,
        "height": height,
        "num_frames": num_frames,
        "fps": fps,
        "seed": seed,
    });
    if let Some(png) = image_png {
        let b64 = base64::engine::general_purpose::STANDARD.encode(png);
        body["image"] = json!(format!("data:image/png;base64,{b64}"));
    }
    if let Some(l) = lora {
        if !l.is_empty() {
            body["lora"] = json!(l);
        }
    }
    run_job(s, "video", body)
}

/// Re-light a clip (MP4 bytes) to match a 360 HDRI environment map using the
/// NVIDIA Relight runtime. `video` + `environment_map` are sent as base64 data
/// URLs so the engine never needs shared storage. `intensity` is 0..1.
pub fn relight_video(
    s: &AppSettings,
    video: &[u8],
    environment_map: &[u8],
    env_filename: &str,
    intensity: f64,
    fps: u32,
    seed: i64,
) -> Result<Vec<u8>, String> {
    let vid_b64 = base64::engine::general_purpose::STANDARD.encode(video);
    // Pick an image mime from the HDRI extension (most are .hdr/.exr/.png/.jpg).
    let env_mime = match env_filename.rsplit('.').next().unwrap_or("").to_ascii_lowercase().as_str() {
        "png" => "image/png",
        "jpg" | "jpeg" => "image/jpeg",
        "exr" => "image/x-exr",
        "webp" => "image/webp",
        _ => "image/x-hdr", // .hdr / radiance
    };
    let env_b64 = base64::engine::general_purpose::STANDARD.encode(environment_map);
    let body = json!({
        "model": "relight",
        "video": format!("data:video/mp4;base64,{vid_b64}"),
        "environment_map": format!("data:{env_mime};base64,{env_b64}"),
        "intensity": intensity.clamp(0.0, 1.0),
        "fps": fps.clamp(8, 60),
        "seed": seed,
    });
    run_job_at(s, "/video/relight", "video", body)
}

/// Generate a music track (WAV bytes) with an installed ACE-Step model.
pub fn generate_music(
    s: &AppSettings,
    prompt: &str,
    model: &str,
    kind: &str,
    duration_seconds: i64,
    lyrics: Option<&str>,
    lora: Option<&str>,
    seed: i64,
) -> Result<Vec<u8>, String> {
    let mut body = json!({
        "prompt": prompt,
        "model": model,
        "kind": kind,
        "duration_seconds": duration_seconds.clamp(4, 300),
        "format": "wav",
        "seed": seed,
    });
    if let Some(l) = lyrics {
        if !l.is_empty() {
            body["lyrics"] = json!(l);
        }
    }
    if let Some(l) = lora {
        if !l.is_empty() {
            body["lora"] = json!(l);
        }
    }
    run_job(s, "music", body)
}

// ---------------------------------------------------------------------------
// Status / discovery
// ---------------------------------------------------------------------------

fn label_for(id: &str, description: &str) -> String {
    if !description.is_empty() {
        description.to_string()
    } else {
        id.to_string()
    }
}

/// Probe the engine: is it configured, reachable, and what models does it serve.
pub fn status(s: &AppSettings) -> EngineStatus {
    let base = match base_url(s) {
        Some(b) => b,
        None => {
            return EngineStatus {
                configured: false,
                reachable: false,
                base_url: String::new(),
                models: vec![],
                message: "Set the AI Engine URL in Settings to use your installed models."
                    .into(),
            };
        }
    };
    let key = api_key(s);

    // /health is unauthenticated.
    let health = get_json(&base, "", "/health", 8);
    if let Err(e) = health {
        return EngineStatus {
            configured: true,
            reachable: false,
            base_url: base.clone(),
            models: vec![],
            message: format!("Engine not reachable at {base}: {e}"),
        };
    }
    let sim = health
        .as_ref()
        .ok()
        .and_then(|v| v.get("simulate").and_then(|x| x.as_bool()))
        .unwrap_or(false);

    // /models requires the API key.
    let mut models: Vec<EngineModel> = vec![];
    match get_json(&base, &key, "/models", 10) {
        Ok(v) => {
            if let Some(map) = v.get("models").and_then(|m| m.as_object()) {
                for (domain, items) in map {
                    if let Some(arr) = items.as_array() {
                        for it in arr {
                            if let Some(id) = it.get("id").and_then(|x| x.as_str()) {
                                let desc = it
                                    .get("description")
                                    .and_then(|x| x.as_str())
                                    .unwrap_or("");
                                models.push(EngineModel {
                                    id: id.to_string(),
                                    domain: domain.clone(),
                                    label: label_for(id, desc),
                                });
                            }
                        }
                    }
                }
            }
        }
        Err(e) => {
            return EngineStatus {
                configured: true,
                reachable: true,
                base_url: base.clone(),
                models: vec![],
                message: format!("Engine reachable but /models failed (check API key): {e}"),
            };
        }
    }

    let msg = if models.is_empty() {
        "Engine reachable but no models advertised.".to_string()
    } else if sim {
        format!("Engine connected (SIMULATION mode) — {} models.", models.len())
    } else {
        format!("Engine connected — {} installed models.", models.len())
    };

    EngineStatus {
        configured: true,
        reachable: true,
        base_url: base,
        models,
        message: msg,
    }
}
